### ISSUE TITLE
Add Accomodation section 

### ISSUE THREAD

**Issue by karilyn** [wexfest/wexfest.com#5]
Got the copy ready to go.

**Comment by simonwex** [comment]
Add the copy here?

**Comment by karilyn** [comment]
Looking for a place to stay in Revelstoke? There are many options available, though book sooner rather than later to ensure you get a place. It's a long weekend with lots of fun events happening in town, including a baseball tournament, a mountain bike race, and the third annual Revelstoke Bike Fest.

We've reserved blocks of rooms at a few hotels. Please reference KEMPTON/WEX when booking. 

Monashee Lodge ($99 + tax): call 250-814-2553 to book. IMPORTANT: Please book before June 5 at the Monashee Lodge. (LINK: http://www.monasheelodgerevelstoke.com/) 
Monashee Lodge offers several different room types if you're travelling with family and friends, all at the same rate, so bunk up! 
Powder Springs Motel ($89 + tax): call 250-837-5151 to book. (LINK: http://powdersprings.ca/) 
A pretty standard motel located right downtown. 

We've also got private house and/or apartment accommodation options through a local property management company. Contact Karilyn or Simon for more information on how to book those. 

There are also camping options available: 
Lamplighter Campground (http://www.lamplightercampground.com/)
KOA Campground (http://koa.com/campgrounds/revelstoke/)
Williamson Lake Campground (http://www.williamsonlakecampground.com/)

You're also welcome to camp right at the wedding venue on Friday and Saturday nights. In fact, we'd love for you to stay out there with us the night of the wedding - that's where we'll be camping! (Just be prepared for loud music and rowdy shenanigans). 

Flying in from out of town and want to camp out the night of the wedding? Let us know in advance and we'll start collecting gear for those who need. There's washrooms, a kitchen and running water, so don't worry about it being too rustic.
